---
- platform: mqtt
  name: "Roomba"
  schema: state
  supported_features:
    - start
    - stop
    - return_home
    - battery
    - clean_spot
  availability_topic: "roomba_001/status"
  state_topic: "roomba_001/state"
  command_topic: "roomba_001/command"